### PR TITLE
Use newer DES API

### PR DESCRIPTION
**Pull request by Legimet**
The old API was removed in OpenSSL 1.1, causing Luna to fail to build. I built the current Ndless installer using this Luna, and it works. I also made some other minor changes.

The ReadMe needs an update, and perhaps the DLL and luna.gif should be removed.

### CODE REVIEW

**Comment by Legimet** [comment]
Also, it turns out that luna.gif is a JPEG file :P

**Comment by Vogtinator** [comment]
> Also, it turns out that luna.gif is a JPEG file :P

I'm speechless. Good thing that this is text :D

Can you bump the version to 0.3 or something and remove the jpeg.gif and .dll?

**Comment by Legimet** [comment]
According to the ReadMe, 0.3 was released in 2012, as was 0.3a.

**Comment by Vogtinator** [comment]
> According to the ReadMe, 0.3 was released in 2012, as was 0.3a.

The readme says it's ```= Luna v0.2b for TI-Nspire =```...
In that case, let's just call it "1.0". It works in most cases, so stable enough...

**Pull request merged**
