### PR TITLE
Readme: add more details about Python scripts conversion.

### PR DESCRIPTION
**Pull request by adriweb**

### CODE REVIEW

**Comment by Legimet** [comment]
Could you also update the usage section to mention that multiple Python scripts can be used?

**Comment by adriweb** [comment]
Yep, done

**Comment by Legimet** [comment]
It also seems like FileSaver.js is no longer used as stated in the Readme?

**Comment by adriweb** [comment]
Indeed, good catch.

**Review by Vogtinator — APPROVED** [review]

**Pull request merged**
